### ISSUE TITLE
Traceback Call Error when trying to playback the frames

### ISSUE THREAD

**Issue by GGorchitsa** [sorecords/true_time_remapping#3]
```
Python: Exception ignored in: <function TTR_RenderSupport.__del__ at 0x0000026BD4FA96C0>
Traceback (most recent call last):
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_support.py", line 294, in __del__
    if hasattr(self, 'tmb') and self.tmb and self.tmb_launch:
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy_types.py", line 813, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type TTR_Render has been removed
Traceback (most recent call last):
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_ops.py", line 277, in invoke
    return self.execute(context)
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_ops.py", line 250, in execute
    self.play_setup(context)
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_support.py", line 149, in play_setup
    raise StatusError ()
true_time_remapping.ttr_support.StatusError
```

Running 3.3.1.
In case it's any help, the scene has multiple cameras, some light physics simulation and a lot of keyframe animation.

UPD:  Getting an error even if it's a new project with nothing, but an animated cube. Using Frames vs Speed doesn't make a difference, however i am able to render out the animation with no problems.
```
Python: Traceback (most recent call last):
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_ops.py", line 277, in invoke
    return self.execute(context)
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_ops.py", line 250, in execute
    self.play_setup(context)
  File "C:\Users\Gorchitsa\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\true_time_remapping\ttr_support.py", line 149, in play_setup
    raise StatusError ()
true_time_remapping.ttr_support.StatusError

```

**Comment by sorecords** [comment]
Thank you! Fixed it in version 1.0.2. Please download the latest update from [Boosty](https://boosty.to/as.blend/posts/6331a005-b563-4574-ba5e-ca6e5fc2c195?share=post_link). Once you've bought this post it should be available for you all the time. Anyway if something goes wrong and you have any problem downloading the latest version, just let me know in the direct messages, and I'll send you the zip file with add-on.
